version: '3.8'
services:
  dev:
    image: ghcr.io/bjoernellens1/pypsa-eur-project:latest
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "8888:8888" # Example: Expose port 8888 for Jupyter notebooks
