name: devcontainers/ci

on:
  push:
    branches:
      - master
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: "/usr/share/zoneinfo/Europe/Amsterdam"
      CACHE_VERSION: 'v1' # Example value, adjust as needed
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        uses: docker/login-action@v3.2.0
        # with:
        #   # Server address of Docker registry. If not set then will default to Docker Hub
        #   registry: # optional
        #   # Username used to log against the Docker registry
        #   username: # optional
        #   # Password or personal access token used to log against the Docker registry
        #   password: # optional
        #   # Specifies whether the given registry is ECR (auto, true or false)
        #   ecr: # optional, default is auto
        #   # Log out from the Docker registry at the end of a job
        #   logout: # optional, default is true
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
          
      - name: Dev Container Build and Run Action
        # You may pin to the exact commit or the version.
        # uses: devcontainers/ci@72700878095f87b851a6c4405a16056caffdc577
        uses: devcontainers/ci@v0.3.1900000328
        with:
          # Image name (including registry)
          imageName: ghcr.io/bjoernellens1/pypsa-eur-project # optional
          # One or more comma-separated image tags (defaults to latest)
          # imageTag: # optional
          # # Platforms for which the image should be built. If omitted, defaults to the platform of the GitHub Actions Runner. Multiple platforms should be comma separated.
          # platform: # optional
          # # Specify the command to run after building the dev container image. Can be omitted to skip starting the container.
          # runCmd: # optional
          # # Specify a child folder (containing a .devcontainer) instead of using the repository root
          # subFolder: # optional
          # # Specify path to checked out folder if not using default (or for testing with nektos/act)
          # checkoutPath: # optional, default is .
          # # Control when images are pushed. Options are never, filter, always. For filter (default), images are pushed if the refFilterForPush and eventFilterForPush conditions are met
          push: always # optional, default is filter
          # # Set the source branches (e.g. refs/heads/main) that are allowed to trigger a push of the dev container image. Leave empty to allow all.
          # refFilterForPush: # optional
          # # Set the event names (e.g. pull_request, push) that are allowed to trigger a push of the dev container image. Defaults to push. Leave empty for all
          # eventFilterForPush: # optional, default is push
          # # Specify environment variables to pass to the docker run command
          # env: # optional
          # # For non-root Dev Containers (i.e. where `remoteUser` is specified), the action attempts to make the container user UID and GID match those of the host user. Set this to true to skip this step (defaults to false)
          # skipContainerUserIdUpdate: # optional
          # # Some steps for building the dev container (e.g. container-features) require generating additional build files. To aid docker build cache re-use, you can use this property to set the path that these files will be generated under and use the actions/cache action to cache that folder across runs
          # userDataFolder: # optional
          # # Specify additional images to use for build caching
          cacheFrom: ghcr.io/bjoernellens1/pypsa-eur-project # optional
          # # Builds the image with `--no-cache` (takes precedence over `cacheFrom`)
          # noCache: # optional
          
